// =============================================================================
// AutoHotkey v2 Generator — Generates .ahk text from EditorState
// =============================================================================
// Depends on: models/types.ts, models/export-format.ts, models/ahk-keycode-map.ts,
//             models/constants.ts, models/jis-us-map.ts, models/action-handler.ts,
//             services/ahk-taphold-template.ts
// Tested by: tests/unit/ahk-generator.test.ts
// Called from: stores/editor.svelte.ts

import { AHK_DIAGNOSTIC_CODES, BASE_LAYER_NAME, MODIFIER_SORT_ORDER } from '$lib/models/constants';
import {
	type AhkGeneratorResult,
	type ExportCompatibilityIssue,
	type ExportConversionNotice
} from '$lib/models/export-format';
import { getAhkKeyMapping, hasAhkMapping } from '$lib/models/ahk-keycode-map';
import type {
	EditorState,
	HoldAction,
	KeyAction,
	KeyActionKey,
	KeyActionTapHold,
	Layer,
	PhysicalKey,
	TapAction
} from '$lib/models/types';
import { visitAction, visitTapAction, visitHoldAction } from '$lib/models/action-handler';
import { JIS_TO_US_MAPPINGS, JIS_TO_US_MAP_BY_KEY, JIS_TO_US_MAP_BY_KANATA_NAME } from '$lib/models/jis-us-map';
import { KEY_REGISTRY } from '$lib/models/key-metadata';
import { THM_CLASS_SOURCE, THM_HEADER_COMMENT } from '$lib/services/ahk-taphold-template';
import * as m from '$lib/paraglide/messages';

/** THM コールバック生成に必要な情報を集約 */
interface ThmCallbackInfo {
	/** ホットキートークン（例: "CapsLock", "SC070", "Space"） */
	hotkeyToken: string;
	/** コールバック関数名（例: "CapsLock_TH"） */
	callbackName: string;
	/** 全レイヤのアクションマップ: layerName → { tapAction, holdAction } | null */
	layerActions: Map<string, { tapAction: TapAction; holdAction: HoldAction } | null>;
	/** キー個別のタイムアウト（tappingTerm と異なる場合のみ値を持つ） */
	perKeyTimeout: number | null;
}

// JIS 配列用ホットキートークン上書き (kanataName → JIS AHK hotkey token)
// AHK v2 では文字ベースでキーを解決するため、JIS 配列上のキー名を使う
const JIS_HOTKEY_TOKEN_MAP: ReadonlyMap<string, string> = new Map([
	['=', 'sc00D'],    // Equal(JIS ^/へ): ^ は AHK 修飾プレフィクスのためスキャンコード
	['[', '@'],        // BracketLeft(JIS @/゛)
	[']', '['],        // BracketRight(JIS [/゜)
	["'", 'sc028'],   // Quote(JIS :/け): : は AHK ホットストリング区切りのためスキャンコード
	['\\', ']'],      // Backslash(JIS ]/む)
	[';', 'sc027'],    // Semicolon(JIS ;/+): ; は AHK コメント開始のためスキャンコード
	['grv', 'sc029'],  // Backquote(JIS 半角/全角): スキャンコードで指定
]);

/** AHK スクリプトを生成する */
export function generateAhk(state: EditorState): AhkGeneratorResult {
	if (!state.template.supportedFormats?.includes('ahk')) {
		return {
			text: '',
			issues: [
				{
					format: 'ahk',
					severity: 'error',
					code: AHK_DIAGNOSTIC_CODES.TEMPLATE_UNSUPPORTED,
					message: m.export_ahkUnsupportedTemplate()
				}
			],
			notices: []
		};
	}

	const notices: ExportConversionNotice[] = [
		...collectConversionNotices(state),
		...collectKanataRecommendationNotice(state)
	];
	const issues = collectCompatibilityIssues(state);
	if (issues.length > 0) {
		return {
			text: '',
			issues,
			notices
		};
	}

	const thmCallbacks = collectThmCallbacks(state);
	const hasTapHold = thmCallbacks.length > 0;
	// THM 管理キーの hotkeyToken セット（レイヤ出力から除外用）
	const thmKeys = new Set(thmCallbacks.map((cb) => cb.hotkeyToken));

	const lines: string[] = [];
	appendHeader(lines, notices, hasTapHold);

	if (hasTapHold) {
		lines.push('');
		appendThmClass(lines);
	}

	lines.push('');
	lines.push(`global currentLayer := "${BASE_LAYER_NAME}"`);
	if (needsCapsLockSuppression(state)) {
		lines.push('SetCapsLockState "AlwaysOff"');
	}

	if (hasTapHold) {
		lines.push('');
		appendThmRegistration(lines, state.tappingTerm, thmCallbacks);
		lines.push('');
		appendThmCallbacks(lines, thmCallbacks, state.jisToUsRemap);
	}

	const nonBaseLayers = state.layers
		.filter((layer) => layer.name !== BASE_LAYER_NAME)
		.sort((left, right) => left.name.localeCompare(right.name));
	const baseLayer = state.layers.find((layer) => layer.name === BASE_LAYER_NAME);

	for (const layer of nonBaseLayers) {
		const layerLines = buildLayerRules(state, layer, thmKeys);
		if (layerLines.length === 0) continue;
		lines.push('');
		lines.push(`#HotIf currentLayer = "${layer.name}"`);
		lines.push(...layerLines);
		lines.push('#HotIf');
	}

	if (baseLayer) {
		const baseLines = buildBaseLayerRules(state, baseLayer, thmKeys);
		if (baseLines.length > 0) {
			lines.push('');
			lines.push(...baseLines);
		}
	}

	return {
		text: lines.join('\n').trimEnd() + '\n',
		issues: [],
		notices
	};
}

function appendHeader(lines: string[], notices: ExportConversionNotice[], hasTapHold: boolean): void {
	lines.push('; ============================================================');
	lines.push('; Generated by haruka');
	lines.push('; AutoHotkey v2 - Requires AutoHotkey v2.0+');
	lines.push('; ============================================================');
	if (hasTapHold) {
		for (const comment of THM_HEADER_COMMENT) {
			lines.push(comment);
		}
		lines.push('; ============================================================');
	}
	if (notices.length > 0) {
		const variantNotices = notices.filter((n) => n.code === 'AHK_VARIANT_NORMALIZED');
		const otherNotices = notices.filter((n) => n.code !== 'AHK_VARIANT_NORMALIZED');
		if (variantNotices.length > 0) {
			lines.push('; Conversion Notices:');
			for (const notice of variantNotices) {
				lines.push(`; - ${notice.headerComment}`);
			}
		}
		for (const notice of otherNotices) {
			lines.push(`;`);
			lines.push(`; Note: ${notice.headerComment}`);
		}
	}
	lines.push('#Requires AutoHotkey v2.0');
	lines.push('#SingleInstance Force');
	lines.push('#UseHook');
}

/** THM クラス定義をインライン出力する */
function appendThmClass(lines: string[]): void {
	lines.push(THM_CLASS_SOURCE);
}

/** THM インスタンス生成＋キー登録を出力する */
function appendThmRegistration(lines: string[], tappingTerm: number, callbacks: ThmCallbackInfo[]): void {
	lines.push('; === TapHold Key Registration ===');
	lines.push(`thm := TapHoldManager(${tappingTerm}, ${tappingTerm}, 1, "$*")`);
	for (const cb of callbacks) {
		if (cb.perKeyTimeout !== null) {
			lines.push(`thm.Add("${cb.hotkeyToken}", ${cb.callbackName}, ${cb.perKeyTimeout})`);
		} else {
			lines.push(`thm.Add("${cb.hotkeyToken}", ${cb.callbackName})`);
		}
	}
}

/** 全レイヤの tap-hold キーを走査し、コールバック情報を収集する */
function collectThmCallbacks(state: EditorState): ThmCallbackInfo[] {
	// tap-hold が設定されたキー ID を収集（ベースレイヤのアクションから）
	const tapHoldKeyIds = new Set<string>();
	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			const action = layer.actions.get(key.id);
			if (action?.type === 'tap-hold') {
				tapHoldKeyIds.add(key.id);
			}
		}
	}

	const callbacks: ThmCallbackInfo[] = [];
	for (const keyId of tapHoldKeyIds) {
		const physicalKey = state.template.keys.find((k) => k.id === keyId);
		if (!physicalKey) continue;

		const hotkeyToken = getHotkeyToken(physicalKey, state.jisToUsRemap);
		if (!hotkeyToken) continue;

		const callbackName = `${hotkeyToken}_TH`;
		const layerActions = new Map<string, { tapAction: TapAction; holdAction: HoldAction } | null>();
		let perKeyTimeout: number | null = null;

		for (const layer of state.layers) {
			const action = layer.actions.get(keyId);
			if (action?.type === 'tap-hold') {
				const normalized = normalizeTapHoldAction(action);
				layerActions.set(layer.name, {
					tapAction: normalized.tapAction,
					holdAction: normalized.holdAction
				});
				// キー個別タイムアウト: tappingTerm と異なる場合のみ
				const timeout = normalized.holdTimeout > 0 ? normalized.holdTimeout : normalized.tapTimeout;
				if (timeout !== state.tappingTerm) {
					perKeyTimeout = timeout;
				}
			} else if (action && action.type !== 'transparent') {
				// 非ベースレイヤで tap-hold 以外のアクションが設定されている場合
				// → コールバック内で分岐する（null = transparent/未設定はスキップ）
				layerActions.set(layer.name, null);
			}
		}

		callbacks.push({ hotkeyToken, callbackName, layerActions, perKeyTimeout });
	}

	return callbacks;
}

/** THM コールバック関数定義を出力する */
function appendThmCallbacks(lines: string[], callbacks: ThmCallbackInfo[], jisRemap: boolean): void {
	lines.push('; === TapHold Callbacks ===');
	for (const cb of callbacks) {
		lines.push(`${cb.callbackName}(isHold, taps, state) {`);
		lines.push('    global currentLayer');

		// レイヤごとのアクションを収集（null エントリはスキップ）
		const activeEntries = [...cb.layerActions.entries()].filter(
			(entry): entry is [string, { tapAction: TapAction; holdAction: HoldAction }] => entry[1] !== null
		);

		if (activeEntries.length === 1) {
			// 単一レイヤ: 分岐なし
			const [, actions] = activeEntries[0];
			appendCallbackBody(lines, actions, jisRemap, '    ');
		} else if (activeEntries.length > 1) {
			// 複数レイヤ: currentLayer による分岐
			let first = true;
			for (const [layerName, actions] of activeEntries) {
				const prefix = first ? 'if' : 'else if';
				lines.push(`    ${prefix} (currentLayer = "${layerName}") {`);
				appendCallbackBody(lines, actions, jisRemap, '        ');
				lines.push('    }');
				first = false;
			}
		}

		lines.push('}');
		lines.push('');
	}
}

/** コールバック内の isHold/tap + state 分岐を出力する */
function appendCallbackBody(
	lines: string[],
	actions: { tapAction: TapAction; holdAction: HoldAction },
	jisRemap: boolean,
	indent: string
): void {
	lines.push(`${indent}if (isHold) {`);
	appendHoldCallbackBody(lines, actions.holdAction, jisRemap, indent + '    ');
	lines.push(`${indent}} else {`);
	appendTapCallbackBody(lines, actions.tapAction, jisRemap, indent + '    ');
	lines.push(`${indent}}`);
}

/** hold ブランチ: state=1 (press) / state=0 (release) の分岐を生成する */
function appendHoldCallbackBody(lines: string[], action: HoldAction, jisRemap: boolean, ind: string): void {
	visitHoldAction(action, {
		key: (a) => {
			const mapping = getAhkKeyMapping(a.value);
			if (!mapping) return;
			if (mapping.sendMode === 'key' && (!a.modifiers || a.modifiers.length === 0)) {
				// 修飾なし + キーモード: state=1 → down、state=0 → up
				lines.push(`${ind}if (state = 1) {`);
				lines.push(`${ind}    Send "{${mapping.sendToken} down}"`);
				lines.push(`${ind}} else {`);
				lines.push(`${ind}    Send "{${mapping.sendToken} up}"`);
				lines.push(`${ind}}`);
			} else {
				// 修飾あり or テキストモード: state=1 で 1 回 Send のみ
				lines.push(`${ind}if (state = 1) {`);
				lines.push(`${ind}    ${buildSendCommand(a, jisRemap)}`);
				lines.push(`${ind}}`);
			}
		},
		'no-op': () => {
			// hold no-op: 何もしない
		},
		'layer-switch': (a) => {
			// state=1 でレイヤ切替、release は何もしない
			lines.push(`${ind}if (state = 1) {`);
			lines.push(`${ind}    currentLayer := "${a.layer}"`);
			lines.push(`${ind}}`);
		},
		'layer-while-held': (a) => {
			// state=1 でレイヤ切替、state=0 で復帰
			lines.push(`${ind}if (state = 1) {`);
			lines.push(`${ind}    currentLayer := "${a.layer}"`);
			lines.push(`${ind}} else {`);
			lines.push(`${ind}    currentLayer := "${BASE_LAYER_NAME}"`);
			lines.push(`${ind}}`);
		}
	});
}

/** tap ブランチ: 従来の Send コマンドと同じ出力 */
function appendTapCallbackBody(lines: string[], action: TapAction, jisRemap: boolean, ind: string): void {
	visitTapAction(action, {
		key: (a) => {
			lines.push(`${ind}${buildSendCommand(a, jisRemap)}`);
		},
		transparent: () => {},
		'no-op': () => {}
	});
}

function collectCompatibilityIssues(state: EditorState): ExportCompatibilityIssue[] {
	const issues: ExportCompatibilityIssue[] = [];

	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			const action = layer.actions.get(key.id);
			if (!action) continue;

			if (layer.name === BASE_LAYER_NAME && isDefaultAction(action, key) && !state.jisToUsRemap) {
				continue;
			}
			if (action.type === 'transparent') {
				continue;
			}

			const sourceKanata = key.kanataName;
			if (!sourceKanata || !hasAhkMapping(sourceKanata)) {
				issues.push(createSourceKeyIssue(layer.name, key));
				continue;
			}

			collectActionIssues(issues, layer.name, key.id, action);
		}
	}

	if (state.jisToUsRemap) {
		const baseLayer = state.layers.find((layer) => layer.name === BASE_LAYER_NAME);
		if (baseLayer) {
			for (const mapping of JIS_TO_US_MAPPINGS) {
				const key = state.template.keys.find((candidate) => candidate.id === mapping.physicalKeyId);
				if (!key?.kanataName || hasAhkMapping(key.kanataName)) continue;
				const action = baseLayer.actions.get(key.id);
				if (!action || isDefaultAction(action, key)) {
					issues.push(createSourceKeyIssue(BASE_LAYER_NAME, key));
				}
			}
		}
	}

	return dedupeIssues(issues);
}

function collectActionIssues(
	issues: ExportCompatibilityIssue[],
	layerName: string,
	keyId: string,
	action: KeyAction
): void {
	visitAction(action, {
		key: (a) => {
			if (!hasAhkMapping(a.value)) {
				issues.push(createTargetKeyIssue(layerName, keyId, a.value));
			}
			if (a.modifiers) {
				for (const modifier of a.modifiers) {
					if (!hasAhkMapping(modifier)) {
						issues.push(createTargetKeyIssue(layerName, keyId, modifier));
					}
				}
			}
		},
		transparent: () => {},
		'no-op': () => {},
		'layer-switch': () => {},
		'layer-while-held': () => {},
		'tap-hold': (a) => {
			collectActionIssues(issues, layerName, keyId, a.tapAction);
			collectActionIssues(issues, layerName, keyId, a.holdAction);
		}
	});
}

function collectConversionNotices(state: EditorState): ExportConversionNotice[] {
	const notices: ExportConversionNotice[] = [];
	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			const action = layer.actions.get(key.id);
			if (action?.type !== 'tap-hold') continue;
			if (action.variant === 'tap-hold') continue;
			notices.push({
				format: 'ahk',
				code: AHK_DIAGNOSTIC_CODES.VARIANT_NORMALIZED,
				layerName: layer.name,
				keyId: key.id,
				originalVariant: action.variant,
				convertedVariant: 'tap-hold',
				message: m.export_ahkVariantNormalized({
					layerName: layer.name,
					keyId: key.id,
					originalVariant: action.variant,
					convertedVariant: 'tap-hold'
				}),
				headerComment: `${layer.name} / ${key.id}: ${action.variant} -> tap-hold`
			});
		}
	}
	return notices;
}

/** CapsLock / KanaMode の tap-hold がある場合に kanata 推奨 notice を生成する */
const KANATA_RECOMMENDED_KEY_IDS = new Set(['CapsLock', 'KanaMode']);

function collectKanataRecommendationNotice(state: EditorState): ExportConversionNotice[] {
	const foundKeys = new Set<string>();
	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			if (!KANATA_RECOMMENDED_KEY_IDS.has(key.id)) continue;
			const action = layer.actions.get(key.id);
			if (action?.type === 'tap-hold') {
				foundKeys.add(key.id);
			}
		}
	}
	if (foundKeys.size === 0) return [];
	const keyNames = [...foundKeys].join(' / ');
	return [{
		format: 'ahk',
		code: AHK_DIAGNOSTIC_CODES.KANATA_RECOMMENDED,
		message: m.export_ahkKanataRecommended({ keyNames }),
		headerComment: `${keyNames} の tap-hold には kanata (.kbd) の使用を推奨します`
	}];
}

function buildLayerRules(state: EditorState, layer: Layer, thmKeys: Set<string>): string[] {
	const lines: string[] = [];
	for (const key of state.template.keys) {
		const action = layer.actions.get(key.id);
		if (!action || action.type === 'transparent') continue;
		// THM 管理キーはコールバック内で処理するためレイヤ出力から除外
		const hotkeyToken = getHotkeyToken(key, state.jisToUsRemap);
		if (hotkeyToken && thmKeys.has(hotkeyToken)) continue;
		appendActionRule(lines, key, normalizeTapHoldAction(action), state.jisToUsRemap);
	}
	trimTrailingBlankLine(lines);
	return lines;
}

function buildBaseLayerRules(state: EditorState, baseLayer: Layer, thmKeys: Set<string>): string[] {
	const lines: string[] = [];

	if (state.jisToUsRemap) {
		appendJisUsRules(lines, state, baseLayer);
	}

	for (const key of state.template.keys) {
		const action = baseLayer.actions.get(key.id);
		if (!action || isDefaultAction(action, key)) continue;
		if (
			state.jisToUsRemap &&
			action.type === 'key' &&
			(!action.modifiers || action.modifiers.length === 0) &&
			JIS_TO_US_MAP_BY_KANATA_NAME.has(action.value)
		) {
			continue;
		}
		if (action.type === 'transparent') continue;
		// THM 管理キーはコールバック内で処理するためベースレイヤ出力から除外
		const hotkeyToken = getHotkeyToken(key, state.jisToUsRemap);
		if (hotkeyToken && thmKeys.has(hotkeyToken)) continue;
		appendActionRule(lines, key, normalizeTapHoldAction(action), state.jisToUsRemap);
	}

	trimTrailingBlankLine(lines);
	return lines;
}

function appendJisUsRules(lines: string[], state: EditorState, baseLayer: Layer): void {
	for (const mapping of JIS_TO_US_MAPPINGS) {
		const key = state.template.keys.find((candidate) => candidate.id === mapping.physicalKeyId);
		if (!key?.kanataName) continue;

		const action = baseLayer.actions.get(key.id);
		const remapped =
			action &&
			action.type === 'key' &&
			(!action.modifiers || action.modifiers.length === 0)
				? JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value)
				: undefined;
		const isDefault = !action || isDefaultAction(action, key);
		const selectedMapping = isDefault ? JIS_TO_US_MAP_BY_KEY.get(key.id) : remapped;
		if (!selectedMapping) continue;

		const sourceToken = getHotkeyToken(key, true);
		if (!sourceToken) continue;

		appendBlock(lines, '*' + sourceToken, [
			'if GetKeyState("Shift", "P")',
			'{',
				`SendText(${quoteForAhk(selectedMapping.usShift)})`,
			'}',
			'else',
			'{',
				`SendText(${quoteForAhk(selectedMapping.usNormal)})`,
			'}'
		]);
		lines.push('');
	}
}

function appendActionRule(lines: string[], key: PhysicalKey, action: KeyAction, jisRemap: boolean): void {
	const hotkeyToken = getHotkeyToken(key, jisRemap);
	if (!hotkeyToken) return;

	if (action.type === 'no-op') {
		lines.push(`${hotkeyToken}::return`);
		lines.push('');
		return;
	}

	// layer-while-held は KeyWait で物理キー状態を監視するため、
	// * プレフィクスで修飾キー状態に関係なく発火させる
	// （tap-hold キーは THM 管理のためここには到達しない）
	const needsWildcard = action.type === 'layer-while-held';
	const displayToken = needsWildcard ? `*${hotkeyToken}` : hotkeyToken;
	appendBlock(lines, displayToken, buildActionBody(action, hotkeyToken, jisRemap));
	lines.push('');
}

function appendBlock(lines: string[], hotkeyToken: string, bodyLines: string[]): void {
	lines.push(`${hotkeyToken}::`);
	lines.push('{');
	for (const bodyLine of bodyLines) {
		lines.push(`    ${bodyLine}`);
	}
	lines.push('}');
}

function buildActionBody(action: KeyAction, waitToken: string, jisRemap: boolean): string[] {
	return visitAction(action, {
		key: (a) => [buildSendCommand(a, jisRemap)],
		transparent: () => ['return'],
		'no-op': () => ['return'],
		'layer-switch': (a) => ['global currentLayer', `currentLayer := "${a.layer}"`],
		'layer-while-held': (a) => [
			'global currentLayer',
			`currentLayer := "${a.layer}"`,
			`KeyWait("${waitToken}")`,
			`currentLayer := "${BASE_LAYER_NAME}"`
		],
		// tap-hold キーは THM コールバックで処理するため、ここには到達しない
		'tap-hold': () => ['return']
	});
}

function buildSendCommand(action: KeyActionKey, jisRemap: boolean): string {
	const targetMapping = getAhkKeyMapping(action.value);
	if (!targetMapping) return 'return';

	const isTextMode = targetMapping.sendMode === 'text';
	const keyToken = isTextMode
		? targetMapping.sendToken
		: `{${targetMapping.sendToken}}`;

	if (!action.modifiers || action.modifiers.length === 0) {
		return isTextMode
			? `SendText(${quoteForAhk(keyToken)})`
			: `Send "${escapeAhkString(keyToken)}"`;
	}

	// JIS リマップ有効時: Shift のみの修飾でテキストモードなら US Shift 文字を直接送信
	if (jisRemap && isTextMode && isShiftOnlyModifiers(action.modifiers)) {
		const usShiftChar = KEY_REGISTRY.get(action.value)?.usShift;
		if (usShiftChar) {
			return `SendText(${quoteForAhk(usShiftChar)})`;
		}
	}

	const sortedModifiers = [...action.modifiers].sort(
		(left, right) => MODIFIER_SORT_ORDER.indexOf(left as (typeof MODIFIER_SORT_ORDER)[number]) - MODIFIER_SORT_ORDER.indexOf(right as (typeof MODIFIER_SORT_ORDER)[number])
	);
	const modifierDown = sortedModifiers
		.map((modifier) => getAhkKeyMapping(modifier))
		.filter((mapping): mapping is NonNullable<typeof mapping> => mapping !== undefined)
		.map((mapping) => `{${mapping.sendToken} down}`)
		.join('');
	const modifierUp = [...sortedModifiers]
		.reverse()
		.map((modifier) => getAhkKeyMapping(modifier))
		.filter((mapping): mapping is NonNullable<typeof mapping> => mapping !== undefined)
		.map((mapping) => `{${mapping.sendToken} up}`)
		.join('');

	if (isTextMode) {
		return `Send "${modifierDown}${escapeAhkSendSpecials(keyToken)}${modifierUp}"`;
	}
	return `Send "${escapeAhkString(modifierDown + keyToken + modifierUp)}"`;
}

function normalizeTapHoldAction(action: KeyActionTapHold): KeyActionTapHold;
function normalizeTapHoldAction(action: KeyAction): KeyAction;
function normalizeTapHoldAction(action: KeyAction): KeyAction {
	if (action.type !== 'tap-hold' || action.variant === 'tap-hold') {
		return action;
	}
	const normalized: KeyActionTapHold = {
		...action,
		variant: 'tap-hold'
	};
	return normalized;
}

function isDefaultAction(action: KeyAction, key: PhysicalKey): boolean {
	if (!key.kanataName) {
		return action.type === 'transparent';
	}
	return (
		action.type === 'key' &&
		action.value === key.kanataName &&
		(!action.modifiers || action.modifiers.length === 0)
	);
}

function getHotkeyToken(key: PhysicalKey, jisRemap: boolean): string | undefined {
	if (!key.kanataName) return undefined;
	if (jisRemap) {
		const jisToken = JIS_HOTKEY_TOKEN_MAP.get(key.kanataName);
		if (jisToken) return jisToken;
	}
	return getAhkKeyMapping(key.kanataName)?.hotkeyToken;
}

function needsCapsLockSuppression(state: EditorState): boolean {
	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			if (key.kanataName !== 'caps') continue;
			const action = layer.actions.get(key.id);
			if (action && !isDefaultAction(action, key)) return true;
		}
	}
	return false;
}

function isShiftOnlyModifiers(modifiers: readonly string[]): boolean {
	return modifiers.length > 0 && modifiers.every((m) => m === 'lsft' || m === 'rsft');
}

function createSourceKeyIssue(layerName: string, key: PhysicalKey): ExportCompatibilityIssue {
	return {
		format: 'ahk',
		severity: 'error',
		code: AHK_DIAGNOSTIC_CODES.KEY_NOT_MAPPED,
		layerName,
		keyId: key.id,
		message: m.export_ahkSourceKeyNotMapped({ layerName, keyId: key.id, keyName: key.kanataName ?? key.id })
	};
}

function createTargetKeyIssue(
	layerName: string,
	keyId: string,
	targetKeyName: string
): ExportCompatibilityIssue {
	return {
		format: 'ahk',
		severity: 'error',
		code: AHK_DIAGNOSTIC_CODES.KEY_NOT_MAPPED,
		layerName,
		keyId,
		message: m.export_ahkTargetKeyNotMapped({ layerName, keyId, keyName: targetKeyName })
	};
}

function dedupeIssues(issues: ExportCompatibilityIssue[]): ExportCompatibilityIssue[] {
	const seen = new Set<string>();
	return issues.filter((issue) => {
		const signature = [issue.code, issue.layerName, issue.keyId, issue.message].join('::');
		if (seen.has(signature)) return false;
		seen.add(signature);
		return true;
	});
}

function escapeAhkString(value: string): string {
	return value.replaceAll('`', '``').replaceAll('"', '""');
}

// AHK v2 文字列リテラルの安全なクォート選択
// " を含む → シングルクォートで囲む（' は '' にエスケープ）
// それ以外 → ダブルクォートで囲む（` は `` に、" は "" にエスケープ）
function quoteForAhk(value: string): string {
	if (value.includes('"')) {
		return `'${value.replaceAll("'", "''")}'`;
	}
	return `"${value.replaceAll('\`', '\`\`')}"`;
}

// Send コマンド内のテキストトークン用個別エスケープ（修飾キー付きテキストモード専用）
function escapeAhkSendSpecials(value: string): string {
	return value
		.replaceAll('`', '``')
		.replace(/[{}]/g, (ch) => ch === '{' ? '{{}' : '{}}')
		.replaceAll('^', '{^}')
		.replaceAll('!', '{!}')
		.replaceAll('+', '{+}')
		.replaceAll('#', '{#}')
		.replaceAll('"', '""');
}

function indent(lines: string[]): string[] {
	return lines.map((line) => `    ${line}`);
}

function trimTrailingBlankLine(lines: string[]): void {
	while (lines.at(-1) === '') {
		lines.pop();
	}
}