// =============================================================================
// AutoHotkey v2 Generator — Generates .ahk text from EditorState
// =============================================================================
// Depends on: models/types.ts, models/export-format.ts, models/ahk-keycode-map.ts,
//             models/constants.ts, models/jis-us-map.ts, models/action-handler.ts
// Tested by: tests/unit/ahk-generator.test.ts
// Called from: stores/editor.svelte.ts

import { AHK_DIAGNOSTIC_CODES, BASE_LAYER_NAME, MODIFIER_SORT_ORDER } from '$lib/models/constants';
import {
	type AhkGeneratorResult,
	type ExportCompatibilityIssue,
	type ExportConversionNotice
} from '$lib/models/export-format';
import { getAhkKeyMapping, hasAhkMapping } from '$lib/models/ahk-keycode-map';
import type {
	EditorState,
	HoldAction,
	KeyAction,
	KeyActionKey,
	KeyActionTapHold,
	Layer,
	PhysicalKey,
	TapAction
} from '$lib/models/types';
import { visitAction, visitTapAction, visitHoldAction } from '$lib/models/action-handler';
import { JIS_TO_US_MAPPINGS, JIS_TO_US_MAP_BY_KEY, JIS_TO_US_MAP_BY_KANATA_NAME } from '$lib/models/jis-us-map';
import * as m from '$lib/paraglide/messages';

/** AHK スクリプトを生成する */
export function generateAhk(state: EditorState): AhkGeneratorResult {
	if (!state.template.supportedFormats?.includes('ahk')) {
		return {
			text: '',
			issues: [
				{
					format: 'ahk',
					severity: 'error',
					code: AHK_DIAGNOSTIC_CODES.TEMPLATE_UNSUPPORTED,
					message: m.export_ahkUnsupportedTemplate()
				}
			],
			notices: []
		};
	}

	const notices = collectConversionNotices(state);
	const issues = collectCompatibilityIssues(state);
	if (issues.length > 0) {
		return {
			text: '',
			issues,
			notices
		};
	}

	const lines: string[] = [];
	appendHeader(lines, notices);

	const nonBaseLayers = state.layers
		.filter((layer) => layer.name !== BASE_LAYER_NAME)
		.sort((left, right) => left.name.localeCompare(right.name));
	const baseLayer = state.layers.find((layer) => layer.name === BASE_LAYER_NAME);

	for (const layer of nonBaseLayers) {
		const layerLines = buildLayerRules(state, layer);
		if (layerLines.length === 0) continue;
		lines.push('');
		lines.push(`#HotIf currentLayer = "${layer.name}"`);
		lines.push(...layerLines);
		lines.push('#HotIf');
	}

	if (baseLayer) {
		const baseLines = buildBaseLayerRules(state, baseLayer);
		if (baseLines.length > 0) {
			lines.push('');
			lines.push(...baseLines);
		}
	}

	return {
		text: lines.join('\n').trimEnd() + '\n',
		issues: [],
		notices
	};
}

function appendHeader(lines: string[], notices: ExportConversionNotice[]): void {
	lines.push('; ============================================================');
	lines.push('; Generated by haruka');
	lines.push('; AutoHotkey v2 - Requires AutoHotkey v2.0+');
	lines.push('; ============================================================');
	if (notices.length > 0) {
		lines.push('; Conversion Notices:');
		for (const notice of notices) {
			lines.push(`; - ${notice.headerComment}`);
		}
	}
	lines.push('#Requires AutoHotkey v2.0');
	lines.push('#SingleInstance Force');
	lines.push('');
	lines.push(`global currentLayer := "${BASE_LAYER_NAME}"`);
}

function collectCompatibilityIssues(state: EditorState): ExportCompatibilityIssue[] {
	const issues: ExportCompatibilityIssue[] = [];

	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			const action = layer.actions.get(key.id);
			if (!action) continue;

			if (layer.name === BASE_LAYER_NAME && isDefaultAction(action, key) && !state.jisToUsRemap) {
				continue;
			}
			if (action.type === 'transparent') {
				continue;
			}

			const sourceKanata = key.kanataName;
			if (!sourceKanata || !hasAhkMapping(sourceKanata)) {
				issues.push(createSourceKeyIssue(layer.name, key));
				continue;
			}

			collectActionIssues(issues, layer.name, key.id, action);
		}
	}

	if (state.jisToUsRemap) {
		const baseLayer = state.layers.find((layer) => layer.name === BASE_LAYER_NAME);
		if (baseLayer) {
			for (const mapping of JIS_TO_US_MAPPINGS) {
				const key = state.template.keys.find((candidate) => candidate.id === mapping.physicalKeyId);
				if (!key?.kanataName || hasAhkMapping(key.kanataName)) continue;
				const action = baseLayer.actions.get(key.id);
				if (!action || isDefaultAction(action, key)) {
					issues.push(createSourceKeyIssue(BASE_LAYER_NAME, key));
				}
			}
		}
	}

	return dedupeIssues(issues);
}

function collectActionIssues(
	issues: ExportCompatibilityIssue[],
	layerName: string,
	keyId: string,
	action: KeyAction
): void {
	visitAction(action, {
		key: (a) => {
			if (!hasAhkMapping(a.value)) {
				issues.push(createTargetKeyIssue(layerName, keyId, a.value));
			}
			if (a.modifiers) {
				for (const modifier of a.modifiers) {
					if (!hasAhkMapping(modifier)) {
						issues.push(createTargetKeyIssue(layerName, keyId, modifier));
					}
				}
			}
		},
		transparent: () => {},
		'no-op': () => {},
		'layer-switch': () => {},
		'layer-while-held': () => {},
		'tap-hold': (a) => {
			collectActionIssues(issues, layerName, keyId, a.tapAction);
			collectActionIssues(issues, layerName, keyId, a.holdAction);
		}
	});
}

function collectConversionNotices(state: EditorState): ExportConversionNotice[] {
	const notices: ExportConversionNotice[] = [];
	for (const layer of state.layers) {
		for (const key of state.template.keys) {
			const action = layer.actions.get(key.id);
			if (action?.type !== 'tap-hold') continue;
			if (action.variant === 'tap-hold') continue;
			notices.push({
				format: 'ahk',
				code: AHK_DIAGNOSTIC_CODES.VARIANT_NORMALIZED,
				layerName: layer.name,
				keyId: key.id,
				originalVariant: action.variant,
				convertedVariant: 'tap-hold',
				message: m.export_ahkVariantNormalized({
					layerName: layer.name,
					keyId: key.id,
					originalVariant: action.variant,
					convertedVariant: 'tap-hold'
				}),
				headerComment: `${layer.name} / ${key.id}: ${action.variant} -> tap-hold`
			});
		}
	}
	return notices;
}

function buildLayerRules(state: EditorState, layer: Layer): string[] {
	const lines: string[] = [];
	for (const key of state.template.keys) {
		const action = layer.actions.get(key.id);
		if (!action || action.type === 'transparent') continue;
		appendActionRule(lines, key, normalizeTapHoldAction(action));
	}
	trimTrailingBlankLine(lines);
	return lines;
}

function buildBaseLayerRules(state: EditorState, baseLayer: Layer): string[] {
	const lines: string[] = [];

	if (state.jisToUsRemap) {
		appendJisUsRules(lines, state, baseLayer);
	}

	for (const key of state.template.keys) {
		const action = baseLayer.actions.get(key.id);
		if (!action || isDefaultAction(action, key)) continue;
		if (
			state.jisToUsRemap &&
			action.type === 'key' &&
			(!action.modifiers || action.modifiers.length === 0) &&
			JIS_TO_US_MAP_BY_KANATA_NAME.has(action.value)
		) {
			continue;
		}
		if (action.type === 'transparent') continue;
		appendActionRule(lines, key, normalizeTapHoldAction(action));
	}

	trimTrailingBlankLine(lines);
	return lines;
}

function appendJisUsRules(lines: string[], state: EditorState, baseLayer: Layer): void {
	for (const mapping of JIS_TO_US_MAPPINGS) {
		const key = state.template.keys.find((candidate) => candidate.id === mapping.physicalKeyId);
		if (!key?.kanataName) continue;

		const action = baseLayer.actions.get(key.id);
		const remapped =
			action &&
			action.type === 'key' &&
			(!action.modifiers || action.modifiers.length === 0)
				? JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value)
				: undefined;
		const isDefault = !action || isDefaultAction(action, key);
		const selectedMapping = isDefault ? JIS_TO_US_MAP_BY_KEY.get(key.id) : remapped;
		if (!selectedMapping) continue;

		const sourceToken = getHotkeyToken(key);
		if (!sourceToken) continue;

		appendBlock(lines, sourceToken, [
			'if GetKeyState("Shift", "P")',
			'{',
				`Send "${escapeAhkString(selectedMapping.usShift)}"`,
			'}',
			'else',
			'{',
				`Send "${escapeAhkString(selectedMapping.usNormal)}"`,
			'}'
		]);
		lines.push('');
	}
}

function appendActionRule(lines: string[], key: PhysicalKey, action: KeyAction): void {
	const hotkeyToken = getHotkeyToken(key);
	if (!hotkeyToken) return;

	if (action.type === 'no-op') {
		lines.push(`${hotkeyToken}::return`);
		lines.push('');
		return;
	}

	appendBlock(lines, hotkeyToken, buildActionBody(action, hotkeyToken));
	lines.push('');
}

function appendBlock(lines: string[], hotkeyToken: string, bodyLines: string[]): void {
	lines.push(`${hotkeyToken}::`);
	lines.push('{');
	for (const bodyLine of bodyLines) {
		lines.push(`    ${bodyLine}`);
	}
	lines.push('}');
}

function buildActionBody(action: KeyAction, waitToken: string): string[] {
	return visitAction(action, {
		key: (a) => [buildSendCommand(a)],
		transparent: () => ['return'],
		'no-op': () => ['return'],
		'layer-switch': (a) => ['global currentLayer', `currentLayer := "${a.layer}"`],
		'layer-while-held': (a) => [
			'global currentLayer',
			`currentLayer := "${a.layer}"`,
			`KeyWait("${waitToken}")`,
			`currentLayer := "${BASE_LAYER_NAME}"`
		],
		'tap-hold': (a) => {
			const normalizedAction = normalizeTapHoldAction(a);
			const timeout = formatTapHoldSeconds(normalizedAction);
			return [
				'global currentLayer',
				`if KeyWait("${waitToken}", "T${timeout}")`,
				'{',
					...indent(buildTapActionBody(normalizedAction.tapAction, waitToken)),
				'}',
				'else',
				'{',
					...indent(buildHoldActionBody(normalizedAction.holdAction, waitToken)),
				'}'
			];
		}
	});
}

function buildTapActionBody(action: TapAction, waitToken: string): string[] {
	return visitTapAction(action, {
		key: (a) => [buildSendCommand(a)],
		transparent: () => ['return'],
		'no-op': () => ['return']
	});
}

function buildHoldActionBody(action: HoldAction, waitToken: string): string[] {
	return visitHoldAction(action, {
		key: (a) => [buildSendCommand(a)],
		'no-op': () => ['return'],
		'layer-switch': (a) => [`currentLayer := "${a.layer}"`],
		'layer-while-held': (a) => [
			`currentLayer := "${a.layer}"`,
			`KeyWait("${waitToken}")`,
			`currentLayer := "${BASE_LAYER_NAME}"`
		]
	});
}

function buildSendCommand(action: KeyActionKey): string {
	const targetMapping = getAhkKeyMapping(action.value);
	if (!targetMapping) return 'return';

	const keyToken =
		targetMapping.sendMode === 'text'
			? targetMapping.sendToken
			: `{${targetMapping.sendToken}}`;

	if (!action.modifiers || action.modifiers.length === 0) {
		return `Send "${escapeAhkString(keyToken)}"`;
	}

	const sortedModifiers = [...action.modifiers].sort(
		(left, right) => MODIFIER_SORT_ORDER.indexOf(left as (typeof MODIFIER_SORT_ORDER)[number]) - MODIFIER_SORT_ORDER.indexOf(right as (typeof MODIFIER_SORT_ORDER)[number])
	);
	const modifierDown = sortedModifiers
		.map((modifier) => getAhkKeyMapping(modifier))
		.filter((mapping): mapping is NonNullable<typeof mapping> => mapping !== undefined)
		.map((mapping) => `{${mapping.sendToken} down}`)
		.join('');
	const modifierUp = [...sortedModifiers]
		.reverse()
		.map((modifier) => getAhkKeyMapping(modifier))
		.filter((mapping): mapping is NonNullable<typeof mapping> => mapping !== undefined)
		.map((mapping) => `{${mapping.sendToken} up}`)
		.join('');

	return `Send "${escapeAhkString(modifierDown + keyToken + modifierUp)}"`;
}

function normalizeTapHoldAction(action: KeyActionTapHold): KeyActionTapHold;
function normalizeTapHoldAction(action: KeyAction): KeyAction;
function normalizeTapHoldAction(action: KeyAction): KeyAction {
	if (action.type !== 'tap-hold' || action.variant === 'tap-hold') {
		return action;
	}
	const normalized: KeyActionTapHold = {
		...action,
		variant: 'tap-hold'
	};
	return normalized;
}

function isDefaultAction(action: KeyAction, key: PhysicalKey): boolean {
	if (!key.kanataName) {
		return action.type === 'transparent';
	}
	return (
		action.type === 'key' &&
		action.value === key.kanataName &&
		(!action.modifiers || action.modifiers.length === 0)
	);
}

function getHotkeyToken(key: PhysicalKey): string | undefined {
	if (!key.kanataName) return undefined;
	return getAhkKeyMapping(key.kanataName)?.hotkeyToken;
}

function createSourceKeyIssue(layerName: string, key: PhysicalKey): ExportCompatibilityIssue {
	return {
		format: 'ahk',
		severity: 'error',
		code: AHK_DIAGNOSTIC_CODES.KEY_NOT_MAPPED,
		layerName,
		keyId: key.id,
		message: m.export_ahkSourceKeyNotMapped({ layerName, keyId: key.id, keyName: key.kanataName ?? key.id })
	};
}

function createTargetKeyIssue(
	layerName: string,
	keyId: string,
	targetKeyName: string
): ExportCompatibilityIssue {
	return {
		format: 'ahk',
		severity: 'error',
		code: AHK_DIAGNOSTIC_CODES.KEY_NOT_MAPPED,
		layerName,
		keyId,
		message: m.export_ahkTargetKeyNotMapped({ layerName, keyId, keyName: targetKeyName })
	};
}

function dedupeIssues(issues: ExportCompatibilityIssue[]): ExportCompatibilityIssue[] {
	const seen = new Set<string>();
	return issues.filter((issue) => {
		const signature = [issue.code, issue.layerName, issue.keyId, issue.message].join('::');
		if (seen.has(signature)) return false;
		seen.add(signature);
		return true;
	});
}

function formatTapHoldSeconds(action: KeyActionTapHold): string {
	const milliseconds = action.holdTimeout > 0 ? action.holdTimeout : action.tapTimeout;
	return (milliseconds / 1000).toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
}

function escapeAhkString(value: string): string {
	return value.replaceAll('"', '""');
}

function indent(lines: string[]): string[] {
	return lines.map((line) => `    ${line}`);
}

function trimTrailingBlankLine(lines: string[]): void {
	while (lines.at(-1) === '') {
		lines.pop();
	}
}