// =============================================================================
// .kbd Generator Service — Generates kanata .kbd text from EditorState
// =============================================================================
// Depends on: models/types.ts, models/jis-us-map.ts, models/constants.ts
// Tested by: tests/unit/kbd-generator.test.ts, tests/unit/kbd-generator-jis-us.test.ts
// Called from: stores/editor.svelte.ts

import type { EditorState, KeyAction, Layer, PhysicalKey } from '$lib/models/types';
import { JIS_TO_US_MAPPINGS, JIS_TO_US_MAP_BY_KEY } from '$lib/models/jis-us-map';
import { BASE_LAYER_NAME, KANATA_CHORD_PREFIX, MODIFIER_SORT_ORDER } from '$lib/models/constants';

/**
 * Generate .kbd text from EditorState
 */
export function generateKbd(state: EditorState): string {
	const lines: string[] = [];

	// G-1: Header comment
	lines.push(';; Generated by kanata-web-config');
	if (state.jisToUsRemap) {
		lines.push(';; Requires kanata v1.4.0+ (fork action)');
	}
	lines.push('');

	// G-2: defcfg
	lines.push('(defcfg');
	lines.push('  process-unmapped-keys yes');
	lines.push(')');
	lines.push('');

	// Group keys by rows (y coordinate)
	const rows = groupKeysByRow(state.template.keys.filter((k) => k.kanataName !== undefined));

	// Calculate column widths for alignment (G-7)
	const kanataKeys = state.template.keys.filter((k) => k.kanataName !== undefined);
	const columnWidths = calculateColumnWidths(rows, state.layers, state.jisToUsRemap);

	// G-3: defsrc
	lines.push('(defsrc');
	for (const row of rows) {
		const rowText = row
			.map((key, i) => {
				const colIdx = getColumnIndex(rows, row, i);
				return padRight(key.kanataName ?? '', columnWidths[colIdx]);
			})
			.join(' ');
		lines.push('  ' + rowText.trimEnd());
	}
	lines.push(')');
	lines.push('');

	// Collect aliases (G-4)
	const jisUsAliases = state.jisToUsRemap ? collectJisUsAliases() : [];
	const aliases = collectAliases(state.layers, kanataKeys, state.tappingTerm);
	const allAliases = [...jisUsAliases, ...aliases];

	// G-4: defalias (only if there are aliases)
	if (allAliases.length > 0) {
		lines.push('(defalias');
		if (jisUsAliases.length > 0) {
			lines.push('  ;; JIS→US conversion aliases');
			for (const alias of jisUsAliases) {
				lines.push(`  ${alias.name} ${alias.value}`);
			}
		}
		if (aliases.length > 0) {
			for (const alias of aliases) {
				lines.push(`  ${alias.name} ${alias.value}`);
			}
		}
		lines.push(')');
		lines.push('');
	}

	// G-5: deflayer for each layer
	for (const layer of state.layers) {
		lines.push(`(deflayer ${layer.name}`);
		for (const row of rows) {
			const rowText = row
				.map((key, i) => {
					// JIS→US: replace 16 target keys in base layer with @jus-* references
					// BUT only when the user hasn't customized the action
					const isBaseLayer = layer.name === BASE_LAYER_NAME;
					const action = layer.actions.get(key.id);
					const isDefault = !action || (action.type === 'key' && action.value === key.kanataName);
					const jisUsMapping = isBaseLayer && state.jisToUsRemap && isDefault
						? JIS_TO_US_MAP_BY_KEY.get(key.id)
						: undefined;
					const text = jisUsMapping
						? `@${jisUsMapping.aliasName}`
						: actionToKanataText(action, key, layer.name, allAliases);
					const colIdx = getColumnIndex(rows, row, i);
					return padRight(text, columnWidths[colIdx]);
				})
				.join(' ');
			lines.push('  ' + rowText.trimEnd());
		}
		lines.push(')');
		lines.push('');
	}

	return lines.join('\n').trimEnd() + '\n';
}

// =============================================================================
// Internal helpers
// =============================================================================

interface Alias {
	name: string;
	value: string;
}

/**
 * Generate 16 JIS→US fork-based aliases from mapping data.
 * See: specs/009-fix-shift-sequence/contracts/kbd-generator-jis-us.md (R-3a〜R-3d)
 *
 * カテゴリ A: S-付きshiftExpr → release-key除去、素キー出力（fork除去可能な場合あり）
 * カテゴリ B: 素キーshiftExpr → unshift で Shift 一時解除
 * カテゴリ C: needsReleaseKey=false → 単純fork（変更なし）
 */
function collectJisUsAliases(): Alias[] {
	return JIS_TO_US_MAPPINGS.map((m) => {
		let value: string;
		if (!m.needsReleaseKey) {
			// カテゴリC: jus-yen, jus-ro — 単純な fork（変更なし）
			value = `(fork ${m.normalExpr} ${m.shiftExpr} (lsft rsft))`;
		} else if (m.shiftExpr.startsWith('S-')) {
			// カテゴリA: S-付き — release-key除去、素キー出力
			const bareKey = m.shiftExpr.slice(2);
			if (bareKey === m.normalExpr) {
				// jus-lbr, jus-rbr: normalExprと一致 → fork不要
				value = m.normalExpr;
			} else {
				value = `(fork ${m.normalExpr} ${bareKey} (lsft rsft))`;
			}
		} else {
			// カテゴリB: 素キー — unshiftでShift一時解除（自動復元）
			value = `(fork ${m.normalExpr} (unshift ${m.shiftExpr}) (lsft rsft))`;
		}
		return { name: m.aliasName, value };
	});
}

function groupKeysByRow(keys: PhysicalKey[]): PhysicalKey[][] {
	const rowMap = new Map<number, PhysicalKey[]>();
	for (const key of keys) {
		const y = key.y;
		if (!rowMap.has(y)) rowMap.set(y, []);
		rowMap.get(y)!.push(key);
	}
	// Sort rows by y, keys within row by x
	return [...rowMap.entries()]
		.sort(([a], [b]) => a - b)
		.map(([, row]) => row.sort((a, b) => a.x - b.x));
}

function getColumnIndex(rows: PhysicalKey[][], row: PhysicalKey[], indexInRow: number): number {
	let globalIdx = 0;
	for (const r of rows) {
		if (r === row) return globalIdx + indexInRow;
		globalIdx += r.length;
	}
	return globalIdx + indexInRow;
}

function calculateColumnWidths(rows: PhysicalKey[][], layers: Layer[], jisToUsRemap: boolean): number[] {
	const widths: number[] = [];
	let colIdx = 0;

	for (const row of rows) {
		for (let i = 0; i < row.length; i++) {
			const key = row[i];
			let maxWidth = (key.kanataName ?? '').length;

			// Account for @jus-* alias references in base layer
			if (jisToUsRemap) {
				const jisUsMapping = JIS_TO_US_MAP_BY_KEY.get(key.id);
				if (jisUsMapping) {
					maxWidth = Math.max(maxWidth, `@${jisUsMapping.aliasName}`.length);
				}
			}

			for (const layer of layers) {
				const action = layer.actions.get(key.id);
				const text = actionToKanataTextRaw(action, key, layer.name);
				maxWidth = Math.max(maxWidth, text.length);
			}

			widths[colIdx] = maxWidth;
			colIdx++;
		}
	}

	return widths;
}

function collectAliases(layers: Layer[], keys: PhysicalKey[], tappingTerm: number): Alias[] {
	const aliases: Alias[] = [];
	const seen = new Set<string>();

	for (const layer of layers) {
		for (const key of keys) {
			const action = layer.actions.get(key.id);
			if (!action) continue;

			if (action.type === 'tap-hold') {
				const name = `${key.kanataName ?? ''}_${layer.name}`;
				if (!seen.has(name)) {
					seen.add(name);
					const dummyKey = key;
					const tapText = actionToKanataTextRaw(action.tapAction, dummyKey, layer.name, 'alias');
					const holdText = actionToKanataTextRaw(action.holdAction, dummyKey, layer.name, 'alias');
					aliases.push({
						name,
						value: `(${action.variant} ${tappingTerm} ${tappingTerm} ${tapText} ${holdText})`
					});
				}
			}
		}
	}

	return aliases;
}

function actionToKanataText(
	action: KeyAction | undefined,
	key: PhysicalKey,
	layerName: string,
	aliases: Alias[]
): string {
	if (!action) return key.kanataName ?? '_';

	// G-6: For tap-hold, reference alias
	if (action.type === 'tap-hold') {
		const aliasName = `${key.kanataName ?? ''}_${layerName}`;
		if (aliases.some((a) => a.name === aliasName)) {
			return `@${aliasName}`;
		}
	}

	return actionToKanataTextRaw(action, key, layerName);
}

/**
 * Convert modifier IDs + value to kanata output syntax
 * - All modifiers have chord prefix → chord syntax: C-S-a
 * - Any modifier lacks chord prefix (rctl/rsft/rmet) → multi syntax: (multi rctl a)
 */
function modifiersToKanata(modifiers: string[], value: string): string {
	const allHavePrefix = modifiers.every((m) => m in KANATA_CHORD_PREFIX);
	const sorted = [...modifiers].sort(
		(a, b) => MODIFIER_SORT_ORDER.indexOf(a as typeof MODIFIER_SORT_ORDER[number]) - MODIFIER_SORT_ORDER.indexOf(b as typeof MODIFIER_SORT_ORDER[number])
	);

	if (allHavePrefix) {
		return sorted.map((m) => KANATA_CHORD_PREFIX[m]).join('-') + '-' + value;
	} else {
		return `(multi ${sorted.join(' ')} ${value})`;
	}
}

function actionToKanataTextRaw(
	action: KeyAction | undefined,
	key: PhysicalKey,
	layerName: string,
	mode: 'layer' | 'alias' = 'layer'
): string {
	if (!action) return mode === 'layer' ? (key.kanataName ?? '_') : '_';

	switch (action.type) {
		case 'key': {
			if (action.modifiers && action.modifiers.length > 0) {
				return modifiersToKanata(action.modifiers, action.value);
			}
			return action.value;
		}
		case 'transparent':
			return '_';
		case 'no-op':
			return 'XX';
		case 'layer-while-held':
			return `(layer-while-held ${action.layer})`;
		case 'layer-switch':
			return `(layer-switch ${action.layer})`;
		case 'tap-hold': {
			if (mode === 'alias') return '_';
			const aliasName = `${key.kanataName ?? ''}_${layerName}`;
			return `@${aliasName}`;
		}
		default:
			return mode === 'layer' ? (key.kanataName ?? '_') : '_';
	}
}

function padRight(str: string, width: number): string {
	return str + ' '.repeat(Math.max(0, width - str.length));
}
