// =============================================================================
// .kbd Generator Service — Generates kanata .kbd text from EditorState
// =============================================================================
// Depends on: models/types.ts, models/jis-us-map.ts, models/constants.ts, models/action-handler.ts
// Tested by: tests/unit/kbd-generator.test.ts, tests/unit/kbd-generator-jis-us.test.ts
// Called from: stores/editor.svelte.ts

import type { EditorState, KeyAction, Layer, PhysicalKey, KbdTargetOs } from '$lib/models/types';
import { visitAction } from '$lib/models/action-handler';
import { JIS_TO_US_MAPPINGS, JIS_TO_US_MAP_BY_KEY, JIS_TO_US_MAP_BY_KANATA_NAME, resolveNormalExpr, resolveShiftExpr } from '$lib/models/jis-us-map';
import { BASE_LAYER_NAME, KANATA_CHORD_PREFIX, MODIFIER_SORT_ORDER } from '$lib/models/constants';
import { resolveKbdAction } from '$lib/models/kbd-target-registry';

/** 内部キー名を kanata 互換キー名に変換（defsrc / deflayer のデフォルト出力用） */
function toKanataKeyName(kanataName: string, target: KbdTargetOs): string {
	const strategy = resolveKbdAction(kanataName, target);
	return strategy.type === 'native-key' ? strategy.kanataToken : kanataName;
}

/**
 * Generate .kbd text from EditorState
 */
export function generateKbd(state: EditorState, target: KbdTargetOs = 'macos'): string {
	const lines: string[] = [];

	// G-1: Header comment
	lines.push(';; Generated by kanata-web-config');
	if (state.jisToUsRemap) {
		lines.push(';; Requires kanata v1.4.0+ (fork action)');
	}
	// wintercept 注意喚起コメント
	const hasKanaKey = state.template.keys.some(k => k.kanataName === 'jp-kana');
	if (target === 'windows' && hasKanaKey) {
		lines.push(';;');
		lines.push(';; NOTE: この設定には deflocalkeys-wintercept セクションが含まれています。');
		lines.push(';; kanata を Interception ドライバー (wintercept) モードで起動してください。');
		lines.push(';; 起動例: kanata.exe --wintercept');
	}
	lines.push('');

	// G-2: defcfg
	lines.push('(defcfg');
	lines.push('  process-unmapped-keys yes');
	lines.push(')');
	lines.push('');

	// G-2.5: deflocalkeys-wintercept（Windows Interception ドライバー対応）
	// kanata の deflocalkeys パーサーは from_u16_windows() で数値を OsCode に変換するため、
	// 渡す値はスキャンコードではなく Windows VK コード。VK_DBE_KATAKANA (241) は
	// OsCode::KEY_KATAKANA (90) にマッピングされ、Interception ドライバーが
	// カタカナ/ひらがなキーに割り当てる OsCode と一致する。
	// ビルトイン kana/katakana は Windows では KEY_HANGEUL (122) に固定されるため使えない。
	if (target === 'windows' && hasKanaKey) {
		lines.push('(deflocalkeys-wintercept');
		lines.push('  katahira 241');
		lines.push(')');
		lines.push('');
	}

	// Group keys by rows (y coordinate)
	const rows = groupKeysByRow(state.template.keys.filter((k) => k.kanataName !== undefined));

	// Calculate column widths for alignment (G-7)
	const kanataKeys = state.template.keys.filter((k) => k.kanataName !== undefined);
	const columnWidths = calculateColumnWidths(rows, state.layers, state.jisToUsRemap, target);

	// G-3: defsrc
	lines.push('(defsrc');
	for (const row of rows) {
		const rowText = row
			.map((key, i) => {
				const colIdx = getColumnIndex(rows, row, i);
				return padRight(toKanataKeyName(key.kanataName ?? '', target), columnWidths[colIdx]);
			})
			.join(' ');
		lines.push('  ' + rowText.trimEnd());
	}
	lines.push(')');
	lines.push('');

	// Collect aliases (G-4)
	const jisUsAliases = state.jisToUsRemap ? collectJisUsAliases(target) : [];
	const aliases = collectAliases(state.layers, kanataKeys, state.tappingTerm, target, state.jisToUsRemap);
	const allAliases = [...jisUsAliases, ...aliases];

	// G-4: defalias (only if there are aliases)
	if (allAliases.length > 0) {
		lines.push('(defalias');
		if (jisUsAliases.length > 0) {
			lines.push('  ;; JIS→US conversion aliases');
			for (const alias of jisUsAliases) {
				lines.push(`  ${alias.name} ${alias.value}`);
			}
		}
		if (aliases.length > 0) {
			for (const alias of aliases) {
				lines.push(`  ${alias.name} ${alias.value}`);
			}
		}
		lines.push(')');
		lines.push('');
	}

	// G-5: deflayer for each layer
	for (const layer of state.layers) {
		lines.push(`(deflayer ${layer.name}`);
		for (const row of rows) {
			const rowText = row
				.map((key, i) => {
					// JIS→US: replace 16 target keys with @jus-* references
					const action = layer.actions.get(key.id);
					// 非ベースレイヤーの未設定キー (!action) は transparent 扱い — JIS→US 変換しない
					const isDefault = action !== undefined
						&& action.type === 'key'
						&& action.value === key.kanataName
						&& (!action.modifiers || action.modifiers.length === 0);
					const jisUsMapping = state.jisToUsRemap
						? isDefault
							? JIS_TO_US_MAP_BY_KEY.get(key.id)
							: (action && action.type === 'key' && (!action.modifiers || action.modifiers.length === 0))
								? JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value)
								: undefined
						: undefined;

					// Shift 修飾付き JIS→US 変換: shiftExpr ベースの単一出力
					let shiftJisUsText: string | undefined;
					if (!jisUsMapping && state.jisToUsRemap
						&& action && action.type === 'key'
						&& hasShiftModifier(action.modifiers)) {
						const shiftMapping = JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value);
						if (shiftMapping) {
							const otherMods = removeShiftModifiers(action.modifiers!);
							const shiftExpr = resolveShiftExpr(shiftMapping, target);
							if (shiftExpr.startsWith('S-')) {
								// カテゴリ A/C: S- 接頭辞を分解して lsft を effectiveMods に追加
								const bareKey = shiftExpr.slice(2);
								const effectiveMods = [...otherMods, 'lsft'];
								shiftJisUsText = modifiersToKanata(effectiveMods, bareKey, target);
							} else if (shiftExpr.startsWith('(')) {
								// S式 (arbitrary-code 等): Shift 込みの完全な式
								if (otherMods.length === 0) {
									shiftJisUsText = shiftExpr;
								} else {
									shiftJisUsText = `(multi ${otherMods.join(' ')} ${shiftExpr})`;
								}
							} else {
								// カテゴリ B: 素キー。Shift は吸収済み
								if (otherMods.length === 0) {
									shiftJisUsText = shiftExpr;
								} else {
									shiftJisUsText = modifiersToKanata(otherMods, shiftExpr, target);
								}
							}
						}
					}

					const text = shiftJisUsText
						? shiftJisUsText
						: jisUsMapping
							? `@${jisUsMapping.aliasName}`
							: actionToKanataText(action, key, layer.name, allAliases, target);
					const colIdx = getColumnIndex(rows, row, i);
					return padRight(text, columnWidths[colIdx]);
				})
				.join(' ');
			lines.push('  ' + rowText.trimEnd());
		}
		lines.push(')');
		lines.push('');
	}

	return lines.join('\n').trimEnd() + '\n';
}

// =============================================================================
// Internal helpers
// =============================================================================

/** action.modifiers に lsft / rsft が含まれるか */
function hasShiftModifier(modifiers: string[] | undefined): boolean {
	return modifiers !== undefined && modifiers.some(m => m === 'lsft' || m === 'rsft');
}

/** action.modifiers から lsft / rsft を除去して残りを返す */
function removeShiftModifiers(modifiers: string[]): string[] {
	return modifiers.filter(m => m !== 'lsft' && m !== 'rsft');
}

interface Alias {
	name: string;
	value: string;
}

/**
 * Generate 16 JIS→US fork-based aliases from mapping data.
 * See: specs/009-fix-shift-sequence/contracts/kbd-generator-jis-us.md (R-3a〜R-3d)
 *
 * カテゴリ A: S-付きshiftExpr → release-key除去、素キー出力（fork除去可能な場合あり）
 * カテゴリ B: 素キーshiftExpr → unshift で Shift 一時解除
 * カテゴリ C: needsReleaseKey=false → 単純fork（変更なし）
 */
function collectJisUsAliases(target: KbdTargetOs): Alias[] {
	return JIS_TO_US_MAPPINGS.map((m) => {
		const normalExpr = resolveNormalExpr(m, target);
		const shiftExpr = resolveShiftExpr(m, target);
		let value: string;
		// S式（arbitrary-code 等）を含む場合は Category A/B ロジックが非対応のため
		// Category C 相当の単純 fork にフォールバック
		const hasSExpr = normalExpr.startsWith('(') || shiftExpr.startsWith('(');
		if (hasSExpr || !m.needsReleaseKey) {
			// カテゴリC / S式: 単純な fork
			value = `(fork ${normalExpr} ${shiftExpr} (lsft rsft))`;
		} else if (shiftExpr.startsWith('S-')) {
			// カテゴリA: S-付き — release-key除去、素キー出力
			const bareKey = shiftExpr.slice(2);
			if (bareKey === normalExpr) {
				// jus-lbr, jus-rbr: normalExprと一致 → fork不要
				value = normalExpr;
			} else {
				value = `(fork ${normalExpr} ${bareKey} (lsft rsft))`;
			}
		} else {
			// カテゴリB: 素キー — unshiftでShift一時解除（自動復元）
			value = `(fork ${normalExpr} (unshift ${shiftExpr}) (lsft rsft))`;
		}
		return { name: m.aliasName, value };
	});
}

function groupKeysByRow(keys: PhysicalKey[]): PhysicalKey[][] {
	const rowMap = new Map<number, PhysicalKey[]>();
	for (const key of keys) {
		const y = key.y;
		if (!rowMap.has(y)) rowMap.set(y, []);
		rowMap.get(y)!.push(key);
	}
	// Sort rows by y, keys within row by x
	return [...rowMap.entries()]
		.sort(([a], [b]) => a - b)
		.map(([, row]) => row.sort((a, b) => a.x - b.x));
}

function getColumnIndex(rows: PhysicalKey[][], row: PhysicalKey[], indexInRow: number): number {
	let globalIdx = 0;
	for (const r of rows) {
		if (r === row) return globalIdx + indexInRow;
		globalIdx += r.length;
	}
	return globalIdx + indexInRow;
}

function calculateColumnWidths(rows: PhysicalKey[][], layers: Layer[], jisToUsRemap: boolean, target: KbdTargetOs): number[] {
	const widths: number[] = [];
	let colIdx = 0;

	for (const row of rows) {
		for (let i = 0; i < row.length; i++) {
			const key = row[i];
			let maxWidth = toKanataKeyName(key.kanataName ?? '', target).length;

			// Account for @jus-* alias references
			if (jisToUsRemap) {
				const jisUsMapping = JIS_TO_US_MAP_BY_KEY.get(key.id);
				if (jisUsMapping) {
					maxWidth = Math.max(maxWidth, `@${jisUsMapping.aliasName}`.length);
				}
				// 全レイヤーのリマップ先が変換対象キーの場合も列幅に反映
				for (const layer of layers) {
					const action = layer.actions.get(key.id);
					if (action && action.type === 'key' && (!action.modifiers || action.modifiers.length === 0)) {
						const remapMapping = JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value);
						if (remapMapping) {
							maxWidth = Math.max(maxWidth, `@${remapMapping.aliasName}`.length);
						}
					}
					// Shift 修飾付き JIS→US 変換後の出力幅も反映
					if (action && action.type === 'key' && hasShiftModifier(action.modifiers)) {
						const shiftMapping = JIS_TO_US_MAP_BY_KANATA_NAME.get(action.value);
						if (shiftMapping) {
							const otherMods = removeShiftModifiers(action.modifiers!);
							const shiftExpr = resolveShiftExpr(shiftMapping, target);
							let shiftText: string;
							if (shiftExpr.startsWith('S-')) {
								const bareKey = shiftExpr.slice(2);
								shiftText = modifiersToKanata([...otherMods, 'lsft'], bareKey, target);
							} else if (shiftExpr.startsWith('(')) {
								shiftText = otherMods.length === 0
									? shiftExpr
									: `(multi ${otherMods.join(' ')} ${shiftExpr})`;
							} else {
								shiftText = otherMods.length === 0
									? shiftExpr
									: modifiersToKanata(otherMods, shiftExpr, target);
							}
							maxWidth = Math.max(maxWidth, shiftText.length);
						}
					}
				}
			}

			for (const layer of layers) {
				const action = layer.actions.get(key.id);
				const text = actionToKanataTextRaw(action, key, layer.name, 'layer', target);
				maxWidth = Math.max(maxWidth, text.length);
			}

			widths[colIdx] = maxWidth;
			colIdx++;
		}
	}

	return widths;
}

function collectAliases(layers: Layer[], keys: PhysicalKey[], tappingTerm: number, target: KbdTargetOs, jisToUsRemap: boolean): Alias[] {
	const aliases: Alias[] = [];
	const seen = new Set<string>();

	for (const layer of layers) {
		for (const key of keys) {
			const action = layer.actions.get(key.id);
			if (!action) continue;

			if (action.type === 'tap-hold') {
				const name = `${key.kanataName ?? ''}_${layer.name}`;
				if (!seen.has(name)) {
					seen.add(name);
					const dummyKey = key;
					let tapText = actionToKanataTextRaw(action.tapAction, dummyKey, layer.name, 'alias', target);
					const holdText = actionToKanataTextRaw(action.holdAction, dummyKey, layer.name, 'alias', target);

					// JIS→US: ベースレイヤーの tap-hold で tap が変換対象キーの場合 @jus-* エイリアスを参照
					if (jisToUsRemap && layer.name === BASE_LAYER_NAME
						&& action.tapAction && action.tapAction.type === 'key'
						&& (!action.tapAction.modifiers || action.tapAction.modifiers.length === 0)) {
						const jisUsMapping = JIS_TO_US_MAP_BY_KANATA_NAME.get(action.tapAction.value);
						if (jisUsMapping) {
							tapText = `@${jisUsMapping.aliasName}`;
						}
					}

					aliases.push({
						name,
						value: `(${action.variant} ${tappingTerm} ${tappingTerm} ${tapText} ${holdText})`
					});
				}
			}
		}
	}

	return aliases;
}

function actionToKanataText(
	action: KeyAction | undefined,
	key: PhysicalKey,
	layerName: string,
	aliases: Alias[],
	target: KbdTargetOs
): string {
	if (!action) return toKanataKeyName(key.kanataName ?? '_', target);

	// G-6: For tap-hold, reference alias
	if (action.type === 'tap-hold') {
		const aliasName = `${key.kanataName ?? ''}_${layerName}`;
		if (aliases.some((a) => a.name === aliasName)) {
			return `@${aliasName}`;
		}
	}

	return actionToKanataTextRaw(action, key, layerName, 'layer', target);
}

/**
 * Convert modifier IDs + value to kanata output syntax
 * - All modifiers have chord prefix → chord syntax: C-S-a
 * - Any modifier lacks chord prefix (rctl/rsft/rmet) → multi syntax: (multi rctl a)
 */
function modifiersToKanata(modifiers: string[], value: string, target: KbdTargetOs): string {
	// target-aware 変換: value をレジストリ経由で解決
	const strategy = resolveKbdAction(value, target);
	let resolvedValue: string;
	switch (strategy.type) {
		case 'native-key': resolvedValue = strategy.kanataToken; break;
		case 'fixed-arbitrary-code': resolvedValue = strategy.kanataExpr; break;
		case 'unsupported':
			throw new Error(`unsupported action: ${value} for target ${target}`);
	}

	const allHavePrefix = modifiers.every((m) => m in KANATA_CHORD_PREFIX);
	const sorted = [...modifiers].sort(
		(a, b) => MODIFIER_SORT_ORDER.indexOf(a as typeof MODIFIER_SORT_ORDER[number]) - MODIFIER_SORT_ORDER.indexOf(b as typeof MODIFIER_SORT_ORDER[number])
	);

	if (allHavePrefix) {
		return sorted.map((m) => KANATA_CHORD_PREFIX[m]).join('-') + '-' + resolvedValue;
	} else {
		return `(multi ${sorted.join(' ')} ${resolvedValue})`;
	}
}

function actionToKanataTextRaw(
	action: KeyAction | undefined,
	key: PhysicalKey,
	layerName: string,
	mode: 'layer' | 'alias' = 'layer',
	target: KbdTargetOs = 'macos'
): string {
	if (!action) return mode === 'layer' ? toKanataKeyName(key.kanataName ?? '_', target) : '_';

	return visitAction(action, {
		key: (a) => {
			if (a.modifiers && a.modifiers.length > 0) {
				return modifiersToKanata(a.modifiers, a.value, target);
			}
			const strategy = resolveKbdAction(a.value, target);
			switch (strategy.type) {
				case 'native-key': return strategy.kanataToken;
				case 'fixed-arbitrary-code': return strategy.kanataExpr;
				case 'unsupported':
					throw new Error(`unsupported action: ${a.value} for target ${target}`);
			}
		},
		transparent: () => '_',
		'no-op': () => 'XX',
		'layer-while-held': (a) => `(layer-while-held ${a.layer})`,
		'layer-switch': (a) => `(layer-switch ${a.layer})`,
		'tap-hold': () => {
			if (mode === 'alias') return '_';
			const aliasName = `${key.kanataName ?? ''}_${layerName}`;
			return `@${aliasName}`;
		}
	});
}

function padRight(str: string, width: number): string {
	return str + ' '.repeat(Math.max(0, width - str.length));
}
