// =============================================================================
// Unit Test: embedShareUrlComment — 形式別コメント挿入ロジック
// =============================================================================

import { describe, it, expect } from 'vitest';
import { embedShareUrlComment } from '$lib/services/export-share-url';

const SHARE_URL = 'https://ohtk79.github.io/haruka-dev/#config=eJxLzs8FAAPbAbY';

describe('embedShareUrlComment', () => {
	describe('kbd 形式', () => {
		it('ヘッダーブロック末尾に ;; Edit: <URL> を追加する', () => {
			const input = [
				';; Generated by kanata-web-config',
				';; Requires kanata v1.4.0+ (fork action)',
				'',
				'(defcfg',
				'  process-unmapped-keys yes',
				')',
			].join('\n');

			const result = embedShareUrlComment(input, 'kbd', SHARE_URL);

			expect(result).toContain(`;;  Edit: ${SHARE_URL}`);
			// URL コメントはヘッダーブロック直後に挿入される
			const lines = result.split('\n');
			const editLineIndex = lines.findIndex(l => l.includes('Edit:'));
			expect(editLineIndex).toBeGreaterThan(0);
			// ヘッダーの ;; 行の後に空セパレーター行 ;; がある
			expect(lines[editLineIndex - 1]).toBe(';;');
			// (defcfg は URL コメントの後に来る
			expect(lines.indexOf('(defcfg')).toBeGreaterThan(editLineIndex);
		});

		it('ヘッダーなしの kbd テキストでは先頭に追加する', () => {
			const input = '(defcfg\n  process-unmapped-keys yes\n)';

			const result = embedShareUrlComment(input, 'kbd', SHARE_URL);

			expect(result.startsWith(`;;  Edit: ${SHARE_URL}`)).toBe(true);
			expect(result).toContain('(defcfg');
		});
	});

	describe('json 形式', () => {
		it('JSON 本体の前に // Edit: <URL> 行を追加する', () => {
			const input = '{\n  "title": "haruka: ANSI 104",\n  "rules": []\n}';

			const result = embedShareUrlComment(input, 'json', SHARE_URL);

			expect(result.startsWith(`// Edit: ${SHARE_URL}\n{`)).toBe(true);
			// JSON 本体は変更されない
			expect(result).toContain('"title": "haruka: ANSI 104"');
		});
	});

	describe('json-unified 形式', () => {
		it('json と同じ形式で // Edit: <URL> を追加する', () => {
			const input = '{\n  "title": "haruka: ANSI 104 (unified)",\n  "rules": []\n}';

			const result = embedShareUrlComment(input, 'json-unified', SHARE_URL);

			expect(result.startsWith(`// Edit: ${SHARE_URL}\n{`)).toBe(true);
			expect(result).toContain('"title": "haruka: ANSI 104 (unified)"');
		});
	});

	describe('ahk 形式', () => {
		it('ヘッダーブロック末尾に ; Edit: <URL> を追加する', () => {
			const input = [
				'; ============================================================',
				'; Generated by haruka',
				'; AutoHotkey v2 - Requires AutoHotkey v2.0+',
				'; ============================================================',
				'#Requires AutoHotkey v2.0',
				'#SingleInstance Force',
			].join('\n');

			const result = embedShareUrlComment(input, 'ahk', SHARE_URL);

			expect(result).toContain(`; Edit: ${SHARE_URL}`);
			const lines = result.split('\n');
			const editLineIndex = lines.findIndex(l => l.includes('Edit:'));
			expect(editLineIndex).toBeGreaterThan(0);
			// セパレーター行 ; がある
			expect(lines[editLineIndex - 1]).toBe(';');
			// #Requires は URL コメントの後に来る
			expect(lines.indexOf('#Requires AutoHotkey v2.0')).toBeGreaterThan(editLineIndex);
		});
	});

	describe('空 URL', () => {
		it('shareUrl が空の場合は元テキストをそのまま返す', () => {
			const input = ';; Generated by kanata-web-config\n\n(defcfg)';

			expect(embedShareUrlComment(input, 'kbd', '')).toBe(input);
		});
	});
});
